# =========================================================================
# WhiteList: Доверенные IP-адреса и подсети KREC
# Формат: <IP или CIDR> 0;
# =========================================================================

# Собственный публичный IP портала krec.kz
79.140.225.194/32 0;

# Офисный пул и диапазон дата-центра KREC (AS43873)
79.140.225.0/24 0;

# Внутренние административные сети управления и мониторинга
10.0.150.0/24 0;
192.168.101.0/24 0;
