user nginx;
worker_processes auto;

error_log /var/log/nginx/error.log warn;
pid /var/run/nginx.pid;

events {
    worker_connections 2048;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    log_format main
        '$remote_addr - $remote_user [$time_local] "$request" '
        '$status $body_bytes_sent "$http_referer" '
        '"$http_user_agent" "$http_x_forwarded_for"';

    access_log /var/log/nginx/access.log main;

    sendfile on;
    tcp_nopush on;
    keepalive_timeout 65;

    client_max_body_size 100m;

    gzip on;
    gzip_types
        text/plain
        text/css
        application/json
        application/javascript
        application/xml
        image/svg+xml;

    upstream kvit_backend {
        server kvit-api:8000;
        keepalive 32;
    }

    # Перенаправление HTTP на HTTPS
    server {
        listen 80;
        listen [::]:80;

        server_name krec.kz;

        location / {
            return 301 https://krec.kz$request_uri;
        }
    }

    server {
        listen 443 ssl;
        listen [::]:443 ssl;
        http2 on;

        server_name krec.kz;

	ssl_certificate /etc/letsencrypt/live/krec.kz-0001/fullchain.pem;
	ssl_certificate_key /etc/letsencrypt/live/krec.kz-0001/privkey.pem;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_session_cache shared:SSL:10m;
        ssl_session_timeout 1d;
        ssl_session_tickets off;

        add_header X-Content-Type-Options nosniff always;
        add_header X-Frame-Options SAMEORIGIN always;
        add_header Referrer-Policy strict-origin-when-cross-origin always;

        location /static/ {
            alias /app/static/;
            access_log off;
            expires 7d;
        }

        location /internal_receipts/ {
            internal;
            alias /app/receipts/;
        }

        error_page 503 @maintenance;
        location @maintenance {
            root /app;
            rewrite ^(.*)$ /static/maintenance.html break;
        }

        location / {
            # Проверка флага технических работ
            if (-f /app/data/maintenance.flag) {
                return 503;
            }

            proxy_pass http://kvit_backend;

            proxy_http_version 1.1;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;

            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";

            proxy_connect_timeout 30s;
            proxy_send_timeout 300s;
            proxy_read_timeout 300s;
        }
    }
}
