# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import receipts_pb2 as proto_dot_receipts__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/receipts_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ReceiptServiceStub:
    """────────── Сервисы gRPC ──────────
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAccount = channel.unary_unary(
                '/receipts.ReceiptService/GetAccount',
                request_serializer=proto_dot_receipts__pb2.AccountRequest.SerializeToString,
                response_deserializer=proto_dot_receipts__pb2.AccountResponse.FromString,
                _registered_method=True)
        self.GetReceipts = channel.unary_unary(
                '/receipts.ReceiptService/GetReceipts',
                request_serializer=proto_dot_receipts__pb2.ReceiptsQuery.SerializeToString,
                response_deserializer=proto_dot_receipts__pb2.ReceiptsListResponse.FromString,
                _registered_method=True)
        self.GetDistinctPeriods = channel.unary_unary(
                '/receipts.ReceiptService/GetDistinctPeriods',
                request_serializer=proto_dot_receipts__pb2.EmptyRequest.SerializeToString,
                response_deserializer=proto_dot_receipts__pb2.PeriodsResponse.FromString,
                _registered_method=True)
        self.GetSystemStats = channel.unary_unary(
                '/receipts.ReceiptService/GetSystemStats',
                request_serializer=proto_dot_receipts__pb2.EmptyRequest.SerializeToString,
                response_deserializer=proto_dot_receipts__pb2.StatsResponse.FromString,
                _registered_method=True)
        self.StreamReceiptPDF = channel.unary_stream(
                '/receipts.ReceiptService/StreamReceiptPDF',
                request_serializer=proto_dot_receipts__pb2.TokenRequest.SerializeToString,
                response_deserializer=proto_dot_receipts__pb2.FileChunk.FromString,
                _registered_method=True)


class ReceiptServiceServicer:
    """────────── Сервисы gRPC ──────────
    """

    def GetAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReceipts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDistinctPeriods(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSystemStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamReceiptPDF(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReceiptServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAccount,
                    request_deserializer=proto_dot_receipts__pb2.AccountRequest.FromString,
                    response_serializer=proto_dot_receipts__pb2.AccountResponse.SerializeToString,
            ),
            'GetReceipts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReceipts,
                    request_deserializer=proto_dot_receipts__pb2.ReceiptsQuery.FromString,
                    response_serializer=proto_dot_receipts__pb2.ReceiptsListResponse.SerializeToString,
            ),
            'GetDistinctPeriods': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDistinctPeriods,
                    request_deserializer=proto_dot_receipts__pb2.EmptyRequest.FromString,
                    response_serializer=proto_dot_receipts__pb2.PeriodsResponse.SerializeToString,
            ),
            'GetSystemStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSystemStats,
                    request_deserializer=proto_dot_receipts__pb2.EmptyRequest.FromString,
                    response_serializer=proto_dot_receipts__pb2.StatsResponse.SerializeToString,
            ),
            'StreamReceiptPDF': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamReceiptPDF,
                    request_deserializer=proto_dot_receipts__pb2.TokenRequest.FromString,
                    response_serializer=proto_dot_receipts__pb2.FileChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'receipts.ReceiptService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('receipts.ReceiptService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReceiptService:
    """────────── Сервисы gRPC ──────────
    """

    @staticmethod
    def GetAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/receipts.ReceiptService/GetAccount',
            proto_dot_receipts__pb2.AccountRequest.SerializeToString,
            proto_dot_receipts__pb2.AccountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetReceipts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/receipts.ReceiptService/GetReceipts',
            proto_dot_receipts__pb2.ReceiptsQuery.SerializeToString,
            proto_dot_receipts__pb2.ReceiptsListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDistinctPeriods(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/receipts.ReceiptService/GetDistinctPeriods',
            proto_dot_receipts__pb2.EmptyRequest.SerializeToString,
            proto_dot_receipts__pb2.PeriodsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSystemStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/receipts.ReceiptService/GetSystemStats',
            proto_dot_receipts__pb2.EmptyRequest.SerializeToString,
            proto_dot_receipts__pb2.StatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamReceiptPDF(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/receipts.ReceiptService/StreamReceiptPDF',
            proto_dot_receipts__pb2.TokenRequest.SerializeToString,
            proto_dot_receipts__pb2.FileChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ReconcileServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetReconcileSummary = channel.unary_unary(
                '/receipts.ReconcileService/GetReconcileSummary',
                request_serializer=proto_dot_receipts__pb2.ReconcileQuery.SerializeToString,
                response_deserializer=proto_dot_receipts__pb2.ReconcileSummaryResponse.FromString,
                _registered_method=True)


class ReconcileServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetReconcileSummary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReconcileServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetReconcileSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReconcileSummary,
                    request_deserializer=proto_dot_receipts__pb2.ReconcileQuery.FromString,
                    response_serializer=proto_dot_receipts__pb2.ReconcileSummaryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'receipts.ReconcileService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('receipts.ReconcileService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReconcileService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetReconcileSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/receipts.ReconcileService/GetReconcileSummary',
            proto_dot_receipts__pb2.ReconcileQuery.SerializeToString,
            proto_dot_receipts__pb2.ReconcileSummaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
